name: AliBot Daily Send

on:
  schedule:
    - cron: '0 7-21/2 * * *' # ירוץ כל שעתיים בשעות אי-זוגיות
  workflow_dispatch: # מאפשר הרצה ידנית

jobs:
  run-bots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run AliExpress Bot
        env:
          GREEN_ID: ${{ secrets.GREEN_API_ID }}
          GREEN_TOKEN: ${{ secrets.GREEN_API_TOKEN }} # הסוד שציינת
          WA_CHAT_ID: ${{ secrets.WA_CHAT_ID }}
          ADMITAD_FEED: ${{ secrets.ADMITAD_FEED }}
        run: node index.js

      - name: Run Amazon Bot
        env:
          GREEN_ID: ${{ secrets.GREEN_API_ID }}
          GREEN_TOKEN: ${{ secrets.GREEN_API_TOKEN }}
          WA_CHAT_ID: ${{ secrets.WA_CHAT_ID }}
          AMAZON_STORE_ID: ${{ secrets.AMAZON_STORE_ID }}
        run: node amazon.js
