name: AliBot Daily Send

on:
  schedule:
    # רץ בכל יום בשעה 08:00 UTC (שזה 10:00 או 11:00 בבוקר בישראל)
    - cron: '0 8 * * *'
  workflow_dispatch: # מאפשר להפעיל את הבוט ידנית לניסיון

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        env:
          GREEN_API_ID: ${{ secrets.GREEN_API_ID }}
          GREEN_API_TOKEN: ${{ secrets.GREEN_API_TOKEN }}
          WA_CHAT_ID: ${{ secrets.WA_CHAT_ID }}
          AMAZON_STORE_ID: ${{ secrets.AMAZON_STORE_ID }}
        run: python bot.py
